### ISSUE TITLE
fscore needs to catch "stock not found" error and continue

### ISSUE THREAD

**Issue by gregorykemp** [gregorykemp/stonks#6]
Got this error on a batch run:

```
Traceback (most recent call last):
  File "C:\Users\gkemp\stonks\fscore.py", line 65, in <module>
    main()
  File "C:\Users\gkemp\stonks\fscore.py", line 44, in main
    temp = stonks(ticker, api_key)
  File "C:\Users\gkemp\stonks\stonks.py", line 83, in __init__
    raise KeyError("Count not find " + symbol + " in Alpha Vantage.")
KeyError: 'Count not find AGNU in Alpha Vantage.'

```

This is not OK.  On batch runs we need to soldier on.  Wrap this in a try block and gracefully handle key errors like this.

**Comment by gregorykemp** [comment]
Commit 20ec349 implements this.
